version: '3.8'

services:
  mydb:
    image: postgres:15
    restart: always
    container_name: PostgreSQL-Server
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    container_name: game_redis
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Seoul

  # 새로 추가된 API 서버 블록
  server-api:
    image: dockdiary/server-api:latest
    restart: always
    container_name: server_api
    ports:
      - "8080:8080" # 외부 접속 포트 8080을 컨테이너 내부 8080으로 연결 (.NET 8.0 기본 포트)
    environment:
      # appsettings.json의 DB 연결 문자열을 환경 변수로 동적 덮어쓰기 (언더바 2개 주의)
      - "ConnectionStrings__DefaultConnection=Host=mydb;Port=5432;Database=${POSTGRES_DATABASE};Username=postgres;Password=${POSTGRES_ROOT_PASSWORD};"
      - TZ=Asia/Seoul
    depends_on:
      - database # postgreSQL이 먼저 켜진 후 API 서버가 켜지도록 순서 보장

volumes:
  postgres_data: