services:

  server-api:
    image: dockdiary/server-api:latest
    restart: always
    container_name: server_api
    ports:
      - "8080:8080"
    environment:
      - "ConnectionStrings__DefaultConnection=Host=mydb;Port=5432;Database=${POSTGRES_DATABASE};Username=${POSTGRES_USERNAME};Password=${POSTGRES_ROOT_PASSWORD};"
      - "ConnectionStrings__RedisConnection=game_redis:6379"
      - "Jwt__Key=${JWT_KEY}"
      - "Jwt__Issuer=${JWT_ISSUER}"
      - "Jwt__Audience=${JWT_AUDIENCE}"
      - TZ=Asia/Seoul
    networks:
      - serverdb_default

networks:
  serverdb_default:
    external: true
